// Static mapping of `<MERIDIAN>-<POINT_NUM>` -> MP3 URL.
//
// This module exists so pre-recorded MP3s can be added later without touching
// the UI or the data file. Whenever an entry is present, the audio system
// prefers it over Web Speech API synthesis.
//
// Files are generated by the backend endpoint POST /api/audio/generate
// (ElevenLabs, multilingual v2) and served as static assets from
// /app/frontend/public/audio/ at URL path /audio/<CODE>-<NUM>.mp3.
//
// The key format is `${meridianCode.toUpperCase()}-${pointNum}`.

const AUDIO_SOURCES = {
  // --- 5-point test batch (approval pending) ---
  "LU-7": "/audio/LU-7.mp3",   // 列缺 Liè Quē
  "LI-4": "/audio/LI-4.mp3",   // 合谷 Hé Gǔ
  "ST-36": "/audio/ST-36.mp3", // 足三里 Zú Sān Lǐ
  "SP-6": "/audio/SP-6.mp3",   // 三阴交 Sān Yīn Jiāo
  "DU-20": "/audio/DU-20.mp3", // 百会 Bǎi Huì
};

/**
 * Resolve a static MP3 URL for a given point, if one is registered.
 * @param {string} meridianCode e.g. "LU"
 * @param {number|string} pointNum e.g. 1
 * @returns {string|undefined}
 */
export const resolveAudioSource = (meridianCode, pointNum) => {
  if (!meridianCode || pointNum === undefined || pointNum === null) return undefined;
  const key = `${String(meridianCode).toUpperCase()}-${pointNum}`;
  return AUDIO_SOURCES[key];
};

export default AUDIO_SOURCES;
